// Generated by https://quicktype.io

export interface DashboardSummary {
  numberOfOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberOfClients: number;
  numberOfProducts: number;
  productsOutOfStock: number;
  lowStock: number;
}
